ARITFACTS_ROOT_DIR_NAME: artifacts

DATA:
  ROOT_DIR_NAME: data

  INGESTION:
    ROOT_DIR_NAME: ingestion
    FEATURE_STORE:
      ROOT_DIR_NAME: feature_store
      ZIP_FILE_NAME: data.zip
    INGESTED: 
      ROOT_DIR_NAME: ingested
      
  TRANSFORMATION:
    ROOT_DIR_NAME: transformation
    TRAIN_DATA_DIR_NAME: train
    VALIDATION_DATA_DIR_NAME: validation
    TEST_DATA_DIR_NAME: test
    TOKENIZER_NAME: tokenizer

MODEL_TRAINER: 
  ROOT_DIR_NAME: model
  BASE_ESTIMATOR_NAME: base_estimator
  FINETUNED_ESTIMATOR_NAME: finetuned_estimator
  PARAMS_FILE_NAME: params.json

