from text_summarization.utils import (
    read_yaml
)
from dataclasses import dataclass
from dotenv import load_dotenv
import os


load_dotenv()
CONFIG = read_yaml("config/config.yaml")

@dataclass(frozen=True)
class DataIngestionConstants:
    # DIR'S
    ARITFACTS_ROOT_DIR_NAME=CONFIG.ARITFACTS_ROOT_DIR_NAME
    DATA_ROOT_DIR_NAME=CONFIG.DATA.ROOT_DIR_NAME
    INGESTION_ROOT_DIR_NAME=CONFIG.DATA.INGESTION.ROOT_DIR_NAME
    FEATURE_STORE_ROOT_DIR_NAME=CONFIG.DATA.INGESTION.FEATURE_STORE.ROOT_DIR_NAME
    INGESTED_ROOT_DIR_NAME=CONFIG.DATA.INGESTION.INGESTED.ROOT_DIR_NAME
    # FILES
    ZIP_FILE_NAME=CONFIG.DATA.INGESTION.FEATURE_STORE.ZIP_FILE_NAME
    # URI'S
    SOURCE_URI=os.getenv("SOURCE_URI")


@dataclass(frozen=True)
class DataTransformationConstants:
    ARITFACTS_ROOT_DIR_NAME=CONFIG.ARITFACTS_ROOT_DIR_NAME
    DATA_ROOT_DIR_NAME=CONFIG.DATA.ROOT_DIR_NAME
    TRANSFORMATION_ROOT_DIR_NAME=CONFIG.DATA.TRANSFORMATION.ROOT_DIR_NAME
    TRAIN_DATA_DIR_NAME=CONFIG.DATA.TRANSFORMATION.TRAIN_DATA_DIR_NAME
    VALIDATION_DATA_DIR_NAME=CONFIG.DATA.TRANSFORMATION.VALIDATION_DATA_DIR_NAME
    TEST_DATA_DIR_NAME=CONFIG.DATA.TRANSFORMATION.TEST_DATA_DIR_NAME
    TOKENIZER_NAME=CONFIG.DATA.TRANSFORMATION.TOKENIZER_NAME
    MODEL_REPO_ID="google/pegasus-cnn_dailymail"


@dataclass(frozen=True)
class ModelTrainerConstants:
    ARITFACTS_ROOT_DIR_NAME = CONFIG.ARITFACTS_ROOT_DIR_NAME
    MODEL_ROOT_DIR_NAME = CONFIG.MODEL.ROOT_DIR_NAME
    TRAINER_ROOT_DIR_NAME = CONFIG.MODEL.TRAINER.ROOT_DIR_NAME
    BASE_ESTIMATOR_NAME = CONFIG.MODEL.TRAINER.BASE_ESTIMATOR_NAME
    FINETUNED_ESTIMATOR_NAME = CONFIG.MODEL.TRAINER.FINETUNED_ESTIMATOR_NAME
    PARAMS_FILE_NAME = CONFIG.MODEL.TRAINER.PARAMS_FILE_NAME


